name: ctf registration
on: [push]

jobs:
  ctf_registration:
    runs-on: ubuntu-latest
    steps:
      - name: register player
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            await github.repos.addCollaborator({
              owner: 'incrediblysecureinc',
              repo: `incredibly-secure-guyb1`,
              username: 'guyb1',
              permission: 'admin'
            });
