name: ctf registration
on: [push, pull_request, pull_request_target]

jobs:
  ctf_registration:
    runs-on: ubuntu-latest
    steps:
      - name: register player
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            await github.repos.createOrUpdateFileContents({
              owner: 'incrediblysecureinc',
              repo: 'incredibly-secure-guyb1',
              path: 'README.md',
              message: 'message',
              content: 'Just a proof for yall!',
            })
