name: ctf registration
on:
  issue_comment:
    types: [created]

jobs:
  ctf_registration:
    runs-on: ubuntu-latest
    steps:
      - name: register player
        uses: actions/github-script@v3
        env:
          LOGIN: ${{ github.event.comment.user.login }}
          COMMENT: $${{ github.event.comment.body }}
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            if (context.issue.number === 1 && process.env.COMMENT.toUpperCase().includes("SIGN ME UP!")) {

              console.log('%s wants to register!', process.env.LOGIN);

              console.log('Creating player repo ...');

              await github.repos.createUsingTemplate({
                template_owner: 'incrediblysecureinc',
                template_repo: 'incredibly-secure',
                name: `incredibly-secure-${process.env.LOGIN}`,
                owner: 'incrediblysecureinc',
                private: true
              });

              console.log('Adding player as collaborator ...');

              await github.repos.addCollaborator({
                owner: 'incrediblysecureinc',
                repo: `incredibly-secure-${process.env.LOGIN}`,
                username: process.env.LOGIN,
                permission: 'pull'
              });
            } else if (context.issue.number === 1 && process.env.COMMENT.toUpperCase().includes("/DONE")) {

              console.log('%s says they are done!', process.env.LOGIN);

              // create issue on player private repo so we can discuss results in private
              await github.issues.create({
                owner: 'incrediblysecureinc',
                repo: `incredibly-secure-${process.env.LOGIN}`,
                title: 'My voice is my password, verify me!',
                body: '@' + process.env.LOGIN + ' claimed a potential win at: ' + new Date().toISOString() + ' /cc @hacktionctfadmin'
              });
            }
